development:
  adapter: postgresql
  encoding: utf8
  database: got_api_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: got_api_test
  pool: 5
  username:
  password:

# production:
#   adapter: postgresql
#   encoding: utf8
#   database: project_production
#   pool: 5
#   username:
#   password:
